public enum LexemeType {
    KEYWORD_INTEGER, KEYWORD_REAL, KEYWORD_BOOLEAN, KEYWORD_IF,
    KEYWORD_THEN, KEYWORD_ELSE, KEYWORD_BEGIN, KEYWORD_END,
    KEYWORD_FOR, KEYWORD_TO, KEYWORD_DO, KEYWORD_SIN,

    ID, LITERAL_INTEGER, LITERAL_REAL, LITERAL_BOOLEAN, COMMA,

    PARENTHESES_OPEN, PARENTHESES_CLOSE, BRACKETS_OPEN,
    BRACKETS_CLOSE, BRACES_OPEN, BRACES_CLOSE,

    SEMICOLON, POINTER,

    OPERATOR_ASSIGN, OPERATOR_PLUS, OPERATOR_MINUS, OPERATOR_MULTIPLY,
    OPERATOR_DIVIDE, OPERATOR_EQUALS, OPERATOR_NOT_EQUALS, OPERATOR_LESS,
    OPERATOR_LESS_OR_EQUALS, OPERATOR_GREATER, OPERATOR_GREATER_OR_EQUALS
}
