enum PieceType {
    OPERATOR_PLUS, OPERATOR_MINUS,
    OPERATOR_MULTIPLY, OPERATOR_DIVIDE,
    OPERATOR_LESS, OPERATOR_LESS_OR_EQUALS,
    OPERATOR_GREATER, OPERATOR_GREATER_OR_EQUALS,
    OPERATOR_EQUALS, OPERATOR_NOT_EQUALS,
    PARENTHESES_OPEN, PARENTHESES_CLOSE,
    EXPRESSION, SIN
}
